# Google OAuth 2.0
#spring.security.oauth2.client.registration.google.client-id=989154480074-jco3nvu67d62mtu6rkv0qd817t1pr1qb.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.scope=email,profile
# Github OAuth 2.0
#spring.security.oauth2.client.registration.github.client-id=Ov23li4Z5lwlPlPQi5QD
#spring.security.oauth2.client.registration.github.client-secret=399bafe052506bc136fcf5ae297b011b5dfa3976
#spring.security.oauth2.client.registration.github.scope=email,profile
# cloudinary configurations
#cloudinary.api.key=Root
#cloudinary.api.secret=788261191661588
#cloudinary.cloud.name=AjNtHmqEZ2PPq2fOlQOfEZLQ218
#Email configurations
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=kailashkumar975954@gmail.com
#spring.mail.password=wcdrlhtbvrknxloc
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

#spring.mail.properties.domain_name=localhost
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
# Github OAuth 2.0
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=email,profile
# cloudinary configurations
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}
cloudinary.cloud.name=${CLOUDINARY_NAME}
#Email configurations
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.domain_name=${EMAIL_DOMAIN}
